### ISSUE TITLE
Oculus-RTC-Demo ERRORS

### ISSUE THREAD

**Issue by EJLimm** [AgoraIO-Community/Unity-VR-Samples#3]
My goal is to have a video conference using Agora video sdk and wearing Oculus Quest2 on Unity.

I proceeded this link(https://github.com/AgoraIO-Community/Unity-VR-Samples/tree/main/Oculus-RTC-Demo) on Unity. I use video sdk version 4.2.6 in the agora website.
By the way, the photo[2] in this readme different from the photo[1] on agoraccontroller, and there is no script in the agoraccontroller. So  I can't write an appID or token.
Also, there are 5 errors on photo[3]. How to resolve this errors?

What should I do?

![1](https://github.com/AgoraIO-Community/Unity-VR-Samples/assets/90162137/eb7d7e7b-49b2-41eb-aabf-25f8199d7e93)
![2](https://github.com/AgoraIO-Community/Unity-VR-Samples/assets/90162137/e55e4be6-f6ec-4445-b751-7cfdb20f3ac5)
![3](https://github.com/AgoraIO-Community/Unity-VR-Samples/assets/90162137/b8c5bed3-a8fa-42b0-95be-e74cd3f57ee9)

**Comment by icywind** [comment]
This is due to incompatible API changes from the Agora SDK.  Will fix in a 4.2.6 update
